import {$,el,busy,showError,teacherRequired,rpc,poll} from './common.js';
const params=new URLSearchParams(location.search),game=params.get('game');
const $$=selector=>Array.from(document.querySelectorAll(selector));
const config={baseball1v1:{title:'1:1 숫자야구',desc:'두 학생이 각자 비밀 숫자를 정하고, 라운드마다 동시에 상대 숫자를 추측합니다.',code:'baseball1v1'},baseball_class:{title:'일대다수 숫자야구',desc:'교사가 정답을 정하면 학생들이 각자 추측합니다. 정답과 시도 횟수로 순위를 확인합니다.',code:'baseball_class'},arithmetic:{title:'사칙연산 챌린지',desc:'학생별로 문제를 풀고 정답 수·점수·걸린 시간을 비교합니다.',code:'arithmetic'}}[game];
if(!config){location.replace('../index.html');throw new Error('잘못된 게임 주소입니다.');}
$('title').textContent=config.title;$('intro').textContent=config.desc;document.title=config.title+' · 수학 게임 교실';
if(game==='baseball_class'){$$('.class-settings').forEach(x=>x.classList.remove('hidden'));}else if(game==='arithmetic'){$$('.arithmetic-settings').forEach(x=>x.classList.remove('hidden'));}else{$$('.baseball-settings').forEach(x=>x.classList.remove('hidden'));}
let roomId=null,state=null,joinUrl='',stopPoll=null,loadingState=false;
const names={WAITING:'참가 대기',SETTING_SECRET:'비밀 숫자 설정',PLAYING:'게임 진행 중',ENDED:'게임 종료',SUCCESS:'홈런 성공',FAILED:'기회 소진',LEFT:'나감',FINISHED:'완주'};
function command(action,room=roomId,settings={}){return rpc('gamehub_teacher_game_command',{p_game:game,p_action:action,p_room:room,p_settings:settings});}
function statusText(s){return names[s]||s||'—';}
async function loadRooms(){const rooms=await command('list',null);$('roomList').replaceChildren(...rooms.map(r=>{const b=el('button',`${r.room_code} · ${statusText(r.status)}`,r.id===roomId?'active':'');b.addEventListener('click',()=>openRoom(r.id));return b;}));if(!rooms.length)$('roomList').append(el('p','아직 만든 방이 없습니다.','muted'));}
function makeSettings(){const roomPassword=$('roomPassword').value;if(game==='baseball1v1')return{roomPassword,digitLength:Number($('digitLength').value),maxRounds:Number($('maxRounds').value),allowZero:$('allowZero').checked};if(game==='baseball_class')return{roomPassword,digitLength:Number($('digitLength').value),maxRounds:Number($('maxRounds').value),allowZero:$('allowZero').checked,answerNumber:$('answerNumber').value.trim()};const selectedOperations=$$('input[name="op"]:checked').map(x=>x.value);return{roomPassword,selectedOperations,totalQuestions:Number($('totalQuestions').value),wrongAnswerMode:$('wrongMode').value,digitSettings:{add:$('digitAdd').value,sub:$('digitSub').value,mul:$('digitMul').value,div:$('digitDiv').value}};}
async function openRoom(id){roomId=id;state=await command('state',id);render();const base=(APP_CONFIG.PUBLIC_APP_URL||location.origin).replace(/\/+$/,'');joinUrl=`${base}/games/competition-join.html?game=${encodeURIComponent(game)}&room=${encodeURIComponent(state.room.room_code)}`;$('joinUrl').value=joinUrl;$('qr').replaceChildren();if(window.QRCode)new QRCode($('qr'),{text:joinUrl,width:220,height:220,correctLevel:QRCode.CorrectLevel.M});$('roomPanel').classList.remove('hidden');await loadRooms();}
function td(row,value){row.append(el('td',String(value??'—')));}
function render(){if(!state)return;const r=state.room;$('roomPanel').classList.remove('hidden');$('roomCode').textContent=r.room_code;$('status').textContent=statusText(r.status);$('progress').textContent=`${state.players.length}명 참가`;
 $('start').classList.toggle('hidden',game==='baseball1v1'||r.status!=='WAITING');$('start').disabled=!state.players.length;$('end').classList.toggle('hidden',r.status==='ENDED');$('startNote').textContent=game==='baseball1v1'?'학생 2명이 입장해 각자 비밀 숫자를 입력하면 자동으로 시작합니다.':game==='baseball_class'?`${r.digit_length}자리 · 최대 ${r.max_rounds}회 · 정답 ${r.answer_number}`:`정답 ${r.total_questions}문제 · ${r.selected_operations.map(x=>({add:'덧셈',sub:'뺄셈',mul:'곱셈',div:'나눗셈'})[x]).join('·')} · 오답 처리 ${r.wrong_answer_mode}`;
 const head=game==='baseball1v1'?['닉네임','준비','활성']:game==='baseball_class'?['학생','상태','시도','마지막 숫자','결과']:['학생','상태','정답','오답','점수','레벨'];$('tableHead').replaceChildren();const tr=el('tr');head.forEach(x=>tr.append(el('th',x)));$('tableHead').append(tr);
 $('playerRows').replaceChildren(...state.players.map(p=>{const row=el('tr');if(game==='baseball1v1'){td(row,p.nickname);td(row,p.has_secret?'비밀 숫자 입력 완료':'입력 대기');td(row,p.is_active?'참가 중':'나감');}else if(game==='baseball_class'){td(row,p.nickname);td(row,statusText(p.status));td(row,p.attempts);td(row,p.last_guess);td(row,p.last_result?(p.last_result.is_home_run?'홈런':p.last_result.is_out?'아웃':`${p.last_result.strikes}S ${p.last_result.balls}B`):'—');}else{td(row,p.nickname);td(row,statusText(p.status));td(row,p.correct_count);td(row,p.wrong_count);td(row,p.score);td(row,p.level);}return row;}));
 if(game==='arithmetic')$('startNote').textContent=`${r.total_questions}문제 · ${(r.selected_operations||[]).map(x=>({add:'덧셈',sub:'뺄셈',mul:'곱셈',div:'나눗셈',square:'제곱',sqrt:'제곱근',cube:'세제곱',fourth:'네제곱',mixed:'복합 문제'})[x]).join('·')} · 오답 처리 ${r.wrong_answer_mode}`;
 if(game==='baseball1v1'){$('recordCard').classList.remove('hidden');$('guessRows').replaceChildren(...(state.guesses||[]).map(g=>{const row=el('tr');td(row,g.round);td(row,g.nickname);td(row,g.guess);td(row,`${g.strikes}S ${g.balls}B`);return row;}));}else $('recordCard').classList.add('hidden');}
async function refresh(){if(!roomId||loadingState)return;loadingState=true;try{const next=await command('state',roomId);state=next;render();}catch(e){showError(e);}finally{loadingState=false;}}
$('createForm').addEventListener('submit',e=>{e.preventDefault();busy($('create'),async()=>{const made=await command('create',null,makeSettings());$('roomPassword').value='';await openRoom(made.id);});});
$('refreshRooms').addEventListener('click',()=>busy($('refreshRooms'),loadRooms));
$('start').addEventListener('click',()=>busy($('start'),async()=>{state=await command('start');render();await loadRooms();}));
$('end').addEventListener('click',()=>busy($('end'),async()=>{if(!confirm('게임을 종료할까요?'))return;state=await command('end');render();await loadRooms();}));
$('delete').addEventListener('click',()=>busy($('delete'),async()=>{if(!confirm('이 방과 게임 기록을 삭제할까요? 학생 계정은 보관됩니다.'))return;await command('delete');roomId=null;state=null;$('roomPanel').classList.add('hidden');await loadRooms();}));
$('copy').addEventListener('click',()=>busy($('copy'),async()=>{try{await navigator.clipboard.writeText(joinUrl);$('msg').textContent='참가 링크를 복사했습니다.';}catch{$('joinUrl').select();throw new Error('링크를 선택했습니다. 길게 눌러 복사하세요.');}}));$('openJoin').addEventListener('click',()=>window.open(joinUrl,'_blank','noopener,noreferrer'));
try{if(await teacherRequired()){await loadRooms();const saved=sessionStorage.getItem('competition_room_'+game);if(saved){try{await openRoom(saved);}catch{sessionStorage.removeItem('competition_room_'+game);}}stopPoll=poll(refresh,5000);}}catch(e){showError(e);}
const oldOpen=openRoom;openRoom=async id=>{await oldOpen(id);sessionStorage.setItem('competition_room_'+game,id);};
window.addEventListener('pagehide',()=>stopPoll?.());
