import {$,el,studentAPI,showError,poll} from './common.js';
const game=new URLSearchParams(location.search).get('game'),sessionKey=`gamehub_${game}_session`;let session=null,state=null,stopPoll=null,busyState=false,submitting=false;
const names={baseball1v1:'1:1 숫자야구',baseball_class:'일대다수 숫자야구',arithmetic:'사칙연산 챌린지'};
try{session=JSON.parse(sessionStorage.getItem(sessionKey)||'null');}catch{}
if(!names[game]||!session?.sessionToken){location.replace(`competition-join.html?game=${encodeURIComponent(game||'')}`);}
$('title').textContent=names[game]||'게임';document.title=$('title').textContent+' · 수학 게임 교실';
async function api(action,data={}){return studentAPI('game',{gameKey:game,gameAction:action,sessionToken:session.sessionToken,data});}
function info(v){$('roomInfo').textContent=`방 ${v.room?.room_code||session.roomCode}`;}
function renderBaseballClass(){const r=state.room,m=state.me;$('status').textContent=r.status==='WAITING'?'선생님이 게임을 시작할 때까지 기다리세요.':r.status==='ENDED'?'게임 종료':`${m.attempts.length} / ${r.max_rounds}회 시도`;$('substatus').textContent=`${r.digit_length}자리 숫자 · 중복 숫자 없음`;$('gameCard').classList.toggle('hidden',r.status!=='PLAYING'||!['WAITING','PLAYING'].includes(m.status));$('prompt').textContent=m.status==='SUCCESS'?'홈런! 정답입니다.':m.status==='FAILED'?'기회를 모두 사용했습니다.':`숫자를 추측하세요 (${m.attempts.length+1}번째)`;$('numberInput').maxLength=r.digit_length;$('numberInput').placeholder=`${r.digit_length}자리 숫자`;$('submit').disabled=m.status!=='PLAYING';
 const attempts=m.attempts||[];historyTable(['회','입력','결과'],attempts.map(a=>[a.attempt,a.guess,a.is_home_run?'홈런':a.is_out?'아웃':`${a.strikes}S ${a.balls}B`]));if(r.answer_number){$('resultCard').classList.remove('hidden');$('resultText').textContent=`정답은 ${r.answer_number}입니다. ${m.status==='SUCCESS'?'성공':'게임 종료'} · ${attempts.length}회 시도`;} }
function render1v1(){const r=state.room,m=state.me,o=state.opponent;$('status').textContent=r.status==='WAITING'?'상대 입장 대기':r.status==='SETTING_SECRET'?'각자 비밀 숫자 입력':r.status==='ENDED'?(r.result_text||'게임 종료'):`${r.current_round} / ${r.max_rounds}라운드`;$('substatus').textContent=o?`상대: ${o.nickname} · ${state.opponent_submitted?'이번 라운드 제출 완료':'이번 라운드 제출 대기'}`:'상대가 아직 입장하지 않았습니다.';$('gameCard').classList.remove('hidden');const waiting=r.status==='WAITING';const secret=r.status==='SETTING_SECRET'&&!m.has_secret;const canGuess=r.status==='PLAYING'&&!state.my_submitted;$('prompt').textContent=waiting?'상대가 입장할 때까지 기다리세요.':secret?'나만의 비밀 숫자를 정하세요.':canGuess?'상대 숫자를 추측하세요.':r.status==='ENDED'?'게임이 끝났습니다.':'상대가 제출할 때까지 기다리세요.';$('inputLabel').classList.toggle('hidden',!(secret||canGuess));$('numberInput').maxLength=r.digit_length;$('numberInput').placeholder=`서로 다른 ${r.digit_length}자리 숫자`;$('submit').classList.toggle('hidden',!(secret||canGuess));$('submit').disabled=submitting;
 if(r.status==='ENDED'){$('resultCard').classList.remove('hidden');$('resultText').textContent=`${r.result_text||'게임 종료'}${m.secret_number?` 내 정답 ${m.secret_number}`:''}${o?.secret_number?` · 상대 정답 ${o.secret_number}`:''}`;}else $('resultCard').classList.add('hidden');historyTable(['라운드','내 추측','내 결과','상대 추측','상대 결과'],(state.records||[]).map(x=>[x.round,x.my_guess,x.my_result,x.opponent_guess,x.opponent_result]));}
function renderArithmetic(){const r=state.room,m=state.me;$('status').textContent=r.status==='WAITING'?'선생님이 시작할 때까지 기다리세요.':r.status==='ENDED'?'교사가 게임을 종료했습니다.':m.status==='FINISHED'?'완주!':m.status==='FAILED'?'게임 종료':`${m.question_number} / ${r.total_questions}번 문제`;$('substatus').textContent=`${m.score}점 · 정답 ${m.correct_count} · 오답 ${m.wrong_count} · 레벨 ${m.level} · ${formatTime(m.elapsed_seconds)}`;$('gameCard').classList.toggle('hidden',r.status!=='PLAYING'||m.status!=='PLAYING');$('prompt').textContent=m.question?.text||'문제를 준비하고 있습니다.';$('inputLabel').classList.remove('hidden');$('numberInput').placeholder='정수 입력';$('submit').classList.remove('hidden');$('submit').disabled=submitting;if(m.status==='FINISHED'||m.status==='FAILED'||r.status==='ENDED'){$('resultCard').classList.remove('hidden');$('resultText').textContent=`점수 ${m.score}점 · 정답 ${m.correct_count}개 · 오답 ${m.wrong_count}개`;}else $('resultCard').classList.add('hidden');}
function historyTable(headers,rows){const table=document.createElement('table'),thead=document.createElement('thead'),hr=document.createElement('tr');headers.forEach(h=>hr.append(el('th',h)));thead.append(hr);table.append(thead);const body=document.createElement('tbody');rows.forEach(values=>{const row=document.createElement('tr');(Array.isArray(values)?values:headers.map(h=>values[h.toLowerCase()])).forEach(v=>row.append(el('td',String(v??'—'))));body.append(row);});table.append(body);$('historyBox').replaceChildren(table);}
function formatTime(s){return `${Math.floor((s||0)/60)}분 ${(s||0)%60}초`;}
function render(){if(!state)return;info(state);if(game==='baseball1v1')render1v1();else if(game==='baseball_class')renderBaseballClass();else renderArithmetic();}
async function refresh(){if(!session||busyState||submitting||document.hidden)return;busyState=true;try{state=await api('state');render();}catch(e){showError(e);}finally{busyState=false;}}
$('answerForm').addEventListener('submit',e=>{e.preventDefault();if(!state||submitting)return;submitting=true;$('submit').disabled=true;const value=$('numberInput').value.trim();(async()=>{try{if(game==='baseball1v1'){const action=state.room.status==='SETTING_SECRET'&&!state.me.has_secret?'set_secret':'guess';await api(action,{number:value});}else if(game==='baseball_class'){const result=await api('guess',{number:value});$('feedback').textContent=result.me?.last_result?`${result.me.last_result.strikes}S ${result.me.last_result.balls}B`:'';}else{const result=await api('answer',{answer:value});$('feedback').textContent=result.correct?`정답! ${result.correct_answer}`:`오답. 정답은 ${result.correct_answer}`;}
 $('numberInput').value='';state=await api('state');render();}catch(err){showError(err);}finally{submitting=false;if(state)render();}})();});
$('leave').addEventListener('click',async()=>{if(!confirm('게임에서 나갈까요?'))return;try{await api('leave');}catch{}sessionStorage.removeItem(sessionKey);location.href='../index.html';});
try{state=await api('state');render();stopPoll=poll(refresh,3500);}catch(e){showError(e);}
window.addEventListener('pagehide',()=>stopPoll?.());
