import {$,el,studentAPI,getSession,clearSession,showError,clearMessage,poll} from './common.js';
import {rules,boardView,history,statusLabel} from './streams-view.js';
let session=getSession(),state=null,selected=-1,placing=false,refreshing=false,stopPoll=null,expired=false,mutationVersion=0;
rules();
if(session?.roomCode)$('rejoin').href='../student.html?room='+encodeURIComponent(session.roomCode);
function fail(e){showError(e);if(e.code==='SESSION_EXPIRED'){expired=true;stopPoll?.();clearSession();$('rejoin').classList.remove('hidden');$('confirm').disabled=true;$('instruction').textContent='다시 참가하면 저장된 보드가 복구됩니다.';$('board').querySelectorAll('button').forEach(b=>b.disabled=true);}}
function render(){if(!state)return;const {room,me}=state;if(!me)return;$('who').textContent=`${me.student_number} ${me.student_name} · ${room.room_code}`;$('status').textContent=statusLabel(room.status);$('score').textContent=me.score;$('turn').textContent=room.current_turn;$('currentCard').textContent=room.current_card||'—';$('progress').textContent=`${state.placed} / ${state.total}명 배치 완료`;const canPlace=room.status==='PLAYING'&&!me.has_placed&&!placing&&!expired;$('board').replaceChildren(...boardView(me.board,{selected,enabled:canPlace,evaluation:me.evaluation,onSelect:i=>{selected=i;render();}}));$('confirm').disabled=!canPlace||selected<0;$('selection').textContent=selected>=0?`${selected+1}번 칸에 ${room.current_card} 배치`:'빈칸을 선택하세요.';$('instruction').textContent=room.status==='WAITING'?'선생님이 게임을 시작할 때까지 기다려 주세요.':room.status==='ENDED'?'게임이 끝났습니다. 구간별 점수와 최종 순위를 확인하세요.':me.has_placed?'배치 완료! 다음 카드를 기다려 주세요.':'카드를 놓을 빈칸을 선택하고 확정하세요.';history(room.history);$('runs').replaceChildren(...me.evaluation.runs.map(r=>el('span',`${r.start+1}~${r.end+1}번: ${r.length}칸 · ${r.score}점`)));if(me.evaluation.starValue!==null)$('runs').append(el('span',`★ = ${me.evaluation.starValue}로 계산`));if(room.status==='ENDED'){$('rankingBox').classList.remove('hidden');$('ranking').replaceChildren(...state.ranking.map(r=>{const row=el('li',undefined,r.isMe?'me':'');row.append(el('span',`${r.rank}위 · ${r.isMe?'나':r.label}`),el('b',r.score+'점'));return row;}));stopPoll?.();}}
async function refresh(){if(refreshing||placing||expired||!session)return;refreshing=true;const version=mutationVersion;try{const data=await studentAPI('state',{sessionToken:session.sessionToken});if(placing||version!==mutationVersion)return;if(state?.room.current_turn!==data.room.current_turn||data.me?.has_placed)selected=-1;state=data;render();clearMessage();$('connection').textContent='연결됨 · '+new Date().toLocaleTimeString('ko-KR');}catch(e){$('connection').textContent='연결 재시도 중';fail(e);}finally{refreshing=false;}}
$('confirm').addEventListener('click',async()=>{if(placing||selected<0||!state||expired)return;const slot=selected,turn=state.room.current_turn;placing=true;mutationVersion++;render();try{state=await studentAPI('place',{sessionToken:session.sessionToken,slot,turn});selected=-1;clearMessage();}catch(e){fail(e);}finally{placing=false;render();} });
$('leave').addEventListener('click',async()=>{if(!confirm('게임 화면에서 나갈까요? 같은 정보로 다시 참가할 수 있습니다. 게임 중이라면 교사에게 알려 주세요.'))return;$('leave').disabled=true;try{if(session)await studentAPI('logout',{sessionToken:session.sessionToken});}catch{}finally{clearSession();location.href=$('rejoin').href;}});
if(!session){showError(new Error('입장 정보가 없습니다. 방 코드로 다시 참가하세요.'));$('rejoin').classList.remove('hidden');}else{await refresh();if(!expired&&state?.room.status!=='ENDED')stopPoll=poll(refresh,3500);}
window.addEventListener('pagehide',()=>stopPoll?.());
