import {$,el,busy,showError,clearMessage,teacherRequired,rpc,poll,downloadJSON} from './common.js';
import {rules,boardView,history,statusLabel} from './streams-view.js';
import {competitionRanks} from './games/streams-rules.js';
let state=null,channel=null,roomId=null,joinURL='',stopPoll=null,refreshing=false,mutating=false,lastRevision=0, mutationVersion=0;
rules();
async function command(action,args={}){mutating=true;mutationVersion++;try{return await rpc('streams_teacher_command',{p_action:action,p_room:roomId,...args});}finally{mutating=false;}}
async function rooms(){const {data,error}=await sb.from('streams_rooms').select('id,room_code,status,created_at').order('created_at',{ascending:false}).limit(30);if(error)throw error;$('roomList').replaceChildren(...data.map(r=>{const b=el('button',`${r.room_code} · ${statusLabel(r.status)}`,r.id===roomId?'active':'');b.addEventListener('click',()=>busy(b,()=>openRoom(r.id)));return b;}));if(!data.length)$('roomList').append(el('p','아직 만든 방이 없습니다.','muted'));}
async function openRoom(id){roomId=id;state=null;lastRevision++;const revision=lastRevision;const data=await rpc('streams_teacher_command',{p_action:'state',p_room:id});if(revision!==lastRevision)return;state=data;render();sessionStorage.setItem('streams_teacher_room',id);joinURL=new URL('../student.html',location.href).href+'?room='+encodeURIComponent(state.room.room_code);$('joinUrl').value=joinURL;$('qr').replaceChildren();if(window.QRCode)new QRCode($('qr'),{text:joinURL,width:220,height:220,correctLevel:QRCode.CorrectLevel.M});else $('qr').append(el('p','QR을 불러오지 못했습니다. 참가 링크 또는 방 코드를 사용하세요.','small'));if(channel)await sb.removeChannel(channel);channel=sb.channel('room-'+id).on('postgres_changes',{event:'*',schema:'public',table:'streams_room_events',filter:'room_id=eq.'+id},()=>refresh()).subscribe();await rooms();}
async function refresh(){if(!roomId||refreshing||mutating)return;refreshing=true;const id=roomId,version=mutationVersion;try{const data=await rpc('streams_teacher_command',{p_action:'state',p_room:id});if(id!==roomId||mutating||version!==mutationVersion)return;state=data;render();$('connection').textContent='연결됨 · '+new Date().toLocaleTimeString('ko-KR');clearMessage();}catch(e){$('connection').textContent='연결 확인 필요';showError(e);}finally{refreshing=false;}}
function render(){if(!state)return;const {room,players,total,placed}=state;$('game').classList.remove('hidden');$('roomCode').textContent=room.room_code;$('status').textContent=statusLabel(room.status);$('turn').textContent=room.current_turn;$('currentCard').textContent=room.current_card||'—';$('progress').textContent=room.status==='WAITING'?`${total}명 참가 · 준비되면 시작하세요`:`${placed} / ${total}명 배치 완료`;$('progressBar').style.width=(total?100*placed/total:0)+'%';$('start').classList.toggle('hidden',room.status!=='WAITING');$('start').disabled=!total;$('next').classList.toggle('hidden',room.status!=='PLAYING');$('next').disabled=placed!==total||room.current_turn>=20;$('end').classList.toggle('hidden',room.status==='ENDED');history(room.history);$('playersTitle').textContent=room.status==='ENDED'?'최종 순위 · 학생 보드':'학생 현황';const ranks=competitionRanks(players.filter(p=>p.is_active));const sorted=room.status==='ENDED'?[...ranks,...players.filter(p=>!p.is_active)]:players;$('players').replaceChildren(...sorted.map(p=>{const article=el('article',undefined,'player'+(!p.is_active?' inactive':''));article.append(el('h3',`${p.rank?p.rank+'위 · ':''}${p.student_number} ${p.student_name}`),el('p',`${p.score}점 · ${!p.is_active?'참가 종료':room.status==='WAITING'?'준비 완료':p.has_placed?'배치 완료':'배치 대기'}`,'small muted'));const b=el('div',undefined,'board');b.append(...boardView(p.board,{mini:true,evaluation:p.evaluation}));article.append(b);if(p.is_active&&room.status!=='ENDED'){const kick=el('button','참가 종료','danger');kick.addEventListener('click',()=>busy(kick,async()=>{if(!confirm(`${p.student_name} 학생의 이번 게임 참가를 종료할까요?`))return;state=await command('kick',{p_player:p.id});render();}));article.append(kick);}return article;}));}
$('createForm').addEventListener('submit',e=>{e.preventDefault();busy($('create'),async()=>{const data=await command('create',{p_room:null,p_password:$('roomPassword').value});$('roomPassword').value='';await openRoom(data.room.id);});});
$('start').addEventListener('click',()=>busy($('start'),async()=>{if(!confirm('모든 학생이 참가했나요? 시작 후에는 새 학생을 받을 수 없습니다.'))return;state=await command('start');render();await rooms();}).finally(render));
$('next').addEventListener('click',()=>busy($('next'),async()=>{state=await command('next');render();}).finally(render));
$('end').addEventListener('click',()=>busy($('end'),async()=>{if(!confirm('지금까지 배치한 카드로 점수를 계산하고 종료할까요?'))return;state=await command('end');render();await rooms();}).finally(render));
$('deleteRoom').addEventListener('click',()=>busy($('deleteRoom'),async()=>{if(!confirm('이 방의 보드·결과·학생 세션을 삭제할까요? 학생 계정 자체는 남습니다.'))return;await command('delete');if(channel)await sb.removeChannel(channel);roomId=null;state=null;sessionStorage.removeItem('streams_teacher_room');$('game').classList.add('hidden');await rooms();}));
$('refreshRooms').addEventListener('click',()=>busy($('refreshRooms'),rooms));
$('copy').addEventListener('click',()=>busy($('copy'),async()=>{try{await navigator.clipboard.writeText(joinURL);$('msg').textContent='참가 링크를 복사했습니다.';}catch{$('joinUrl').select();throw new Error('링크를 선택했습니다. Ctrl+C 또는 길게 눌러 복사하세요.');}}));
$('newTab').addEventListener('click',()=>window.open(joinURL,'_blank','noopener,noreferrer'));
$('export').addEventListener('click',()=>{if(state)downloadJSON(`streams-${state.room.room_code}-기록.json`,{...state,exportedAt:new Date().toISOString()});});
try{if(await teacherRequired()){await rooms();const saved=sessionStorage.getItem('streams_teacher_room');if(saved){try{await openRoom(saved);}catch{sessionStorage.removeItem('streams_teacher_room');roomId=null;$('msg').textContent='이전 방을 불러올 수 없습니다. 목록에서 선택하세요.';}}stopPoll=poll(refresh,5000);}}catch(e){showError(e);}
window.addEventListener('pagehide',()=>{stopPoll?.();if(channel)sb.removeChannel(channel);});
