import test from 'node:test';import assert from 'node:assert/strict';
import {createStudentHandler} from '../supabase/functions/_shared/student-handler.ts';
const env={ALLOWED_ORIGINS:'https://class.example',SUPABASE_URL:'https://project.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'test-service-key'};
function harness(results={}){const calls=[];const handler=createStudentHandler(env,async(url,init)=>{const name=url.split('/').pop();calls.push({name,args:JSON.parse(init.body),headers:init.headers});if(results[name] instanceof Error)return Response.json({code:'P0001',message:results[name].message},{status:400});return Response.json(name in results?results[name]:name==='gamehub_consume_limit'?true:{ok:true});});return{handler,calls};}
const request=(body,origin='https://class.example')=>new Request('https://project.supabase.co/functions/v1/student-api',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
const join={action:'join',roomCode:'ab12cd34',roomPassword:'room1234',studentNumber:'10101',studentName:'학생',studentPassword:'pass1234'};
test('origin allowlist denies unexpected origins, fail-closed when absent',async()=>{assert.equal((await harness().handler(request(join,'https://evil.example'))).status,403);assert.equal((await createStudentHandler({...env,ALLOWED_ORIGINS:''})(request(join))).status,503);});
test('preflight supports POST and custom apikey header',async()=>{const r=await harness().handler(new Request('https://example.test',{method:'OPTIONS',headers:{Origin:'https://class.example'}}));assert.equal(r.status,204);assert.match(r.headers.get('Access-Control-Allow-Headers'),/apikey/);});
test('join uses persistent rate limits before database password check',async()=>{const {handler,calls}=harness();const r=await handler(request(join));assert.equal(r.status,200);assert.deepEqual(calls.map(c=>c.name),['gamehub_consume_limit','gamehub_consume_limit','streams_join']);assert.equal(calls[2].args.p_code,'AB12CD34');assert.equal(r.headers.get('Cache-Control'),'no-store');});
test('new game join uses common student identity and game-specific SQL session',async()=>{const {handler,calls}=harness();const r=await handler(request({action:'game_join',gameKey:'baseball1v1',roomCode:'ab12cd34',roomPassword:'room1234',studentNumber:'10101',studentName:'학생',studentPassword:'personal123'}));assert.equal(r.status,200);assert.deepEqual(calls.map(c=>c.name),['gamehub_consume_limit','gamehub_consume_limit','gamehub_join_game']);assert.equal(calls.at(-1).args.p_game,'baseball1v1');assert.equal(calls.at(-1).args.p_code,'AB12CD34');});
test('new game action routes only allowlisted actions and server-owned session tokens',async()=>{const {handler,calls}=harness();const token='a'.repeat(64);assert.equal((await handler(request({action:'game',gameKey:'arithmetic',gameAction:'answer',sessionToken:token,data:{answer:'42'}}))).status,200);assert.equal(calls.at(-1).name,'gamehub_student_game_command');assert.deepEqual(Object.keys(calls.at(-1).args).sort(),['p_action','p_data','p_game','p_token']);const count=calls.length;assert.equal((await handler(request({action:'game',gameKey:'arithmetic',gameAction:'guess',sessionToken:token,data:{number:'123'}}))).status,400);assert.equal(calls.length,count);});
test('rate limit stops password attempts',async()=>{const {handler,calls}=harness({gamehub_consume_limit:false});assert.equal((await handler(request(join))).status,429);assert.equal(calls.length,1);});
test('forged, missing token and out-of-range slots are rejected',async()=>{const {handler,calls}=harness();assert.equal((await handler(request({action:'state',sessionToken:'x'}))).status,401);assert.equal((await handler(request({action:'place',sessionToken:'a'.repeat(64),turn:1,slot:20}))).status,400);assert.equal(calls.length,0);});
test('expired token translates to structured unauthorized response',async()=>{const r=await harness({streams_student_command:new Error('SESSION_EXPIRED')}).handler(request({action:'state',sessionToken:'a'.repeat(64)}));assert.equal(r.status,401);assert.equal((await r.json()).code,'SESSION_EXPIRED');});
test('browser cannot submit a card, score, student id or room id to placement RPC',async()=>{const {handler,calls}=harness();await handler(request({action:'place',sessionToken:'b'.repeat(64),slot:3,turn:4,card:'30',score:9999,studentId:'forged',roomId:'forged'}));assert.deepEqual(Object.keys(calls.at(-1).args).sort(),['p_action','p_slot','p_token','p_turn']);});
test('oversized JSON is rejected',async()=>assert.equal((await harness().handler(request({action:'join',text:'x'.repeat(5000)}))).status,413));
test('unknown action and null body rejected',async()=>{assert.equal((await harness().handler(request({action:'teacher-delete'}))).status,400);assert.equal((await harness().handler(request(null))).status,400);});
