import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir,access} from 'node:fs/promises';import path from 'node:path';
const root=new URL('../',import.meta.url);
test('every HTML script and stylesheet path exists; no inline handlers or remote executable code',async()=>{for(const f of ['index.html','student.html','teacher.html','games/streams.html','games/streams-student.html','games/competition.html','games/competition-join.html','games/competition-play.html']){const file=new URL(f,root),s=await readFile(file,'utf8');assert.doesNotMatch(s,/\son\w+=/i);for(const match of s.matchAll(/(?:src|href)="([^"]+)"/g)){const ref=match[1];if(ref.includes('?')||ref.startsWith('#'))continue;assert.doesNotMatch(ref,/^https?:/);await access(new URL(ref,file));}}});
test('three implemented games have registry entries and game-specific tables use isolated prefixes',async()=>{const registry=await readFile(new URL('js/games/registry.js',root),'utf8'),schema=await readFile(new URL('supabase/schema.sql',root),'utf8'),teacher=await readFile(new URL('games/competition.html',root),'utf8');for(const game of ['baseball1v1','baseball_class','arithmetic']){assert.match(registry,new RegExp(`key:'${game}'.*enabled:true`));}for(const table of ['baseball1v1_rooms','baseball1v1_players','baseball1v1_guesses','baseballclass_rooms','baseballclass_players','baseballclass_guesses','arithmetic_rooms','arithmetic_players'])assert.match(schema,new RegExp(`create table if not exists public\\.${table}`));for(const op of ['square','sqrt','cube','fourth','mixed'])assert.match(teacher,new RegExp(`value="${op}"`));assert.match(schema,/한 방에는 100명까지 참가할 수 있습니다/);});
test('only safe static assets are in deployment output',async()=>{for(const forbidden of ['supabase','tests','README.md','.env','scripts'])await assert.rejects(access(new URL('dist/'+forbidden,root)));await access(new URL('dist/index.html',root));});
test('no student session token in a navigation URL',async()=>{for(const dir of ['js'])for(const f of await readdir(new URL(dir+'/',root))){if(!f.endsWith('.js'))continue;assert.doesNotMatch(await readFile(new URL(dir+'/'+f,root),'utf8'),/[?&]token=/);}});

import {resolvePublicAppUrl} from '../scripts/public-url.mjs';
test('QR selects Vercel production host rather than the protected preview host',()=>{assert.equal(resolvePublicAppUrl('', 'math-class.vercel.app'),'https://math-class.vercel.app');assert.equal(resolvePublicAppUrl('https://class.example','preview-123.vercel.app'),'https://class.example');assert.equal(resolvePublicAppUrl('', ''),'');assert.throws(()=>resolvePublicAppUrl('https://class.example/student.html',''));});
